### ISSUE TITLE
Bearer token error with multi-tenancy

### ISSUE THREAD

**Issue by t-dias** [magenta-aps/libreoffice-online-repo#7]
Hello,
I'm using Alfresco Community - 5.2.0 with this module and trying to edit files in libreoffice online:
> http*://libreoffice.docker.localhost/loleaflet/dist/loleaflet.html?WOPISrc=http*://docker.localhost/alfresco/service/wopi/files/0503eed5-6a0e-4267-9c1f-a27806bf7b4a&access_token=rdku2gf3p9rgvce916jone295s

If multi-tenancy is not activated works well and the file is returned.
If multi-tenancy is activated (added one tenant) alfresco return an exception: 
```
alfresco_1_3bb94ade36e7 |  2018-12-20 17:12:46,580  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-4] Exception from executeScript: 11200006 Authorization 'Bearer' not supported.
alfresco_1_3bb94ade36e7 |  org.springframework.extensions.webscripts.WebScriptException: 11200006 Authorization 'Bearer' not supported.
alfresco_1_3bb94ade36e7 | 	at org.alfresco.repo.web.scripts.servlet.BasicHttpAuthenticatorFactory$BasicHttpAuthenticator.authenticate(BasicHttpAuthenticatorFactory.java:200)
alfresco_1_3bb94ade36e7 | 	at org.alfresco.repo.web.scripts.servlet.RemoteUserAuthenticatorFactory$RemoteUserAuthenticator.authenticate(RemoteUserAuthenticatorFactory.java:140)
alfresco_1_3bb94ade36e7 | 	at org.alfresco.repo.web.scripts.RepositoryContainer.authenticate(RepositoryContainer.java:721)
alfresco_1_3bb94ade36e7 | 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:157)
alfresco_1_3bb94ade36e7 | 	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
alfresco_1_3bb94ade36e7 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1_3bb94ade36e7 | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1_3bb94ade36e7 | 	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1_3bb94ade36e7 | 	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
alfresco_1_3bb94ade36e7 | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
alfresco_1_3bb94ade36e7 | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
alfresco_1_3bb94ade36e7 | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
alfresco_1_3bb94ade36e7 | 	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
alfresco_1_3bb94ade36e7 | 	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
alfresco_1_3bb94ade36e7 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
alfresco_1_3bb94ade36e7 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
alfresco_1_3bb94ade36e7 | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
alfresco_1_3bb94ade36e7 | 	at java.lang.Thread.run(Thread.java:745)
```
Can somebody help me please?

**Comment by DarkStar1** [comment]
I'm sorry for replying so late. I have had no reason to look into this module and due to irl issues, this just sort of dropped off my radar.
The error you're experiencing is an alfresco related issue and I can not comment on why you're having the issue as I've not had any experience with multi-tenancy nor are the documents any help when it comes to multi-tenancy.
I hope you've been able to resolve it. If not try the [Order Of the Bee](https://discordapp.com/channels/471285144108662785/471285144687345665) discord channel
